module.exports = function(grunt) {
  grunt.initConfig({
    site_data: grunt.file.readJSON('website.json'),

    sass: {
      dist: {
        files: {
          'build/css/app.css': 'src/sass/style.scss'
        },
        options: {
          style: 'expanded',
          sourcemap: 'none',
          lineNumbers: true
        }
      }
    },
    concat: {
      js: {
        src: ['src/js/vendor/**/*.js', 'src/js/*.js'],
        dest: 'js/core.js',
        options: {
          banner: '/**\n' +
                  ' * (c) <%= grunt.template.today("yyyy") %> Cairn Agency <http://cairnagency.co.uk>\n' +
                  ' */\n\n'
        }
      },
      vendor_css: {
        src: ['src/css/**/*.css'],
        dest: 'build/css/vendor.css'
      },
      css: {
        src: ['build/css/vendor.css', 'build/css/app.css'],
        dest: 'build/css/style.css',
        options: {
          banner: '/**\n' +
                  ' * Theme Name: <%= site_data.theme_name %>\n' +
                  ' * Author: <a href="http://cairnagency.co.uk/">Cairn Agecy</a>\n' +
                  ' * Author URI: http://cairnagency.co.uk/\n' +
                  ' * Version: <%= site_data.version %>\n' +
                  ' * Description: <%= site_data.description %>\n' +
                  ' * Template: cairn-base\n' +
                  ' */\n\n',
          footer: '/* DO NOT EDIT THIS FILE! */\n' +
                  '/* to make changes, create a file called hacks.css and put them in there */\n' +
                  '/* DO NOT EDIT THIS FILE! */'
        }
      }
    },
    jshint: {
      options: {
        indent: 2,
        eqeqeq: true,
        latedef: true,
        noarg: true,
        undef: true,
        unused: true,
        trailing: true,
        reporterOutput: '',
        globals: {
          jQuery: true,
          $: true,
          Modernizr: true,
          console: true,
          alert: true
        },
        browser: true
      },
      files: ['src/js/*.js', '!src/js/vendor/*']
    },
    autoprefixer: {
      build: {
        src: 'build/css/style.css',
        dest: 'style.css'
      }
    },
    clean: {
      build: ['build']
    },
    watch: {
      css: {
        files: ['src/css/**/*.css'],
        tasks: ['sass', 'concat:vendor_css', 'concat:css', 'autoprefixer', 'clean'],
        options: {
          livereload: true
        }
      },
      html: {
        files: ['src/*.html'],
        options: {
          livereload: true
        }
      },
      sass: {
        files: ['src/sass/**/*.scss'],
        tasks: ['sass', 'concat:vendor_css', 'concat:css', 'autoprefixer', 'clean'],
        options: {
          livereload: true
        }
      },
      js: {
        files: ['src/js/**/*.js', 'src/js/*.js'],
        tasks: ['jshint', 'concat:js'],
        options: {
          livereload: true
        }
      },
      php: {
        files: ['*.php', '**/*.php'],
        options: {
          livereload: true
        }
      },
      site_config: {
        files: ['website.json'],
        tasks: ['sass', 'concat:vendor_css', 'concat:css', 'autoprefixer', 'clean'],
        options: {
          livereload: true
        }
      }
    },
    connect: {
      server: {
        options: {
          port: 9001,
          base: '.',
          hostname: '127.0.0.1',
          open: {
            target: 'http://127.0.0.1:9001/src/'
          }
        }
      }
    }
  });

  grunt.loadNpmTasks('grunt-contrib-jshint');
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-contrib-concat');
  grunt.loadNpmTasks('grunt-contrib-sass');
  grunt.loadNpmTasks('grunt-contrib-clean');
  grunt.loadNpmTasks('grunt-autoprefixer');
  grunt.loadNpmTasks('grunt-contrib-connect');


  grunt.registerTask('build', 'Check, concat, minify, etc. In short: build the site', function() {
    grunt.task.run('sass');
    grunt.task.run('concat:vendor_css');
    grunt.task.run('concat:css');
    grunt.task.run('autoprefixer');
    grunt.task.run('jshint');
    grunt.task.run('concat:js');
    grunt.task.run('clean');
  });

  grunt.registerTask('default', 'LET\'S GET TO WORK!', function() {
    grunt.task.run('build');
    grunt.task.run('watch');
  });

  grunt.registerTask('run', 'replacing gulp', function() {
    grunt.task.run('build');
    grunt.task.run('connect');
    grunt.task.run('watch');
  });

};
